In [10]:
#Chi-Square test of independence
from scipy.stats import chi2_contingency 
import pandas as pd
data = pd.read_csv("C:\\Users\\maheh\\Downloads\\Chi-square data.csv")
data


Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               240          360    600

Test of Hypothesis:
Null Hypothesis (H0): There is no significant association between the satisfaction levels and 
    the use of smart devices (independence).

Alternative Hypothesis (H1): There is a significant association between the satisfaction levels and
    the use of smart devices (dependence).

In [35]:
#calculating chi-square stattistic
contingency_table=pd.crosstab(data["Satisfaction"],[data["Smart Thermostat"],data["Smart Light"]])
chi2, p, dof , expected=chi2_contingency(contingency_table)

print("Chi-Square Statistic:",chi2)
print("p-value:", p)
print("Degrees of Freedom:",dof)
print("Expected Frequencies:",expected)

Chi-Square Statistic: 30.000000000000014
p-value: 0.22428900483440342
Degrees of Freedom: 25
Expected Frequencies: [[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


In [26]:
from scipy.stats import chi2

# Degrees of Freedom (dof)
dof = len(contingency_table.index) - 1

# Significance level
alpha = 0.05

# Critical value
#critical_value = chi2.ppf(1 - alpha, dof)
critical_value = chi2.ppf(0.95, dof) # Using 0.95 for a 5% significance level

print(f'Critical Value: {critical_value}')


Critical Value: 11.070497693516351


In [28]:
chi2_stat=30.000000000000014
if chi2_stat > critical_value:
    print("H0 is rejected and H1 is accepted")
    
else:
    print("H0 is accepted and H1 is rejected")

H0 is rejected and H1 is accepted


Conclusion:There is a significant association between the satisfaction levels and
    the use of smart devices (dependence).

------> HYPOTHESIS TESTING

Null Hypothesis (H0): The weekly operating cost model W=$,000+$5X is accurate.

Alternative Hypothesis (H1): The actual weekly operating costs are higher than the model suggests.
    
Sample mean (x) = Rs. 3,050

Theoretical mean (μ) = $1,000 + $5 * 600 = $4,000

Standard deviation (σ) = 5 * 25 = 125
Sample size (n) = 25



In [30]:
import numpy as np

# Given values
sample_mean = 3050
theoretical_mean = 1000 + 5 * 600
std_dev = 5 * 25
sample_size = 25

# Calculate the test statistic (t)
t_statistic = (sample_mean - theoretical_mean) / (std_dev / np.sqrt(sample_size))

print("Test Statistic:",t_statistic)



Test Statistic: -38.0


In [31]:
from scipy.stats import norm
alpha=0.05
critical_value=norm.ppf(1-alpha,dof)
critical_value

6.644853626951472

In [33]:
if t_statistic > critical_value:
    print("H0 is rejected and H1 is accepted")
else:
    print("H0 is accpeted and H1 is rejected")

H0 is accpeted and H1 is rejected


Conlusion:Here is strong evidence to support the restaurant owners
    claim that the weekly operating costs are higher than the model suggests.